PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>

select ?poi
where { 
		?poi a <poiURI>; 
				geo:hasGeometry ?poiGeom. 
				?poiGeom geo:asWKT ?poiWKT. 
		?poi1 a <poi1URI>; 
				geo:hasGeometry ?poi1Geom. 
				?poi1Geom geo:asWKT ?poi1WKT.  
        FILTER(geof:sfWithin(?poiWKT,?poi1WKT)).
}